services:
  mysql:
    image: mysql:8.0
    container_name: aibug-mysql

    command: --default-authentication-plugin=mysql_native_password

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: aibugdb

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - ai-bug-repo-nw


  redis:
    image: redis:7-alpine
    
    ports:
      - "6379:6379"

    networks:
      - ai-bug-repo-nw


  api:
    build: .
    container_name: aibugapi

    command: uvicorn backend.main:app --host 0.0.0.0 --port 8085 --reload

    restart: always

    volumes:
      - ./app:/app

    ports:
      - "8085:8085"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: aibugdb

      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/0

      OLLAMA_HOST: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3
      

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ai-bug-repo-nw


  worker:
    build: .

    command: celery -A backend.services.tasks worker --loglevel=info

    restart: always

    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: aibugdb

      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379/0

      OLLAMA_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3

    depends_on:
      - mysql
      - redis

    networks:
      - ai-bug-repo-nw


  frontend:
    image: nginx:alpine

    ports:
      - "8080:80"

    volumes:
      - ./app/frontend/dashboard:/usr/share/nginx/html

    depends_on:
      - api

    networks:
      - ai-bug-repo-nw
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     -  "11434:11434"
  #   volumes: 
  #     - ollama_data:/root/.ollama

  #   networks:
  #     - ai-bug-repo-nw
volumes:
  mysql-data:
  ollama_data:

networks:
  ai-bug-repo-nw: